sebk_projektor:
    resource: "@SebkProjektorBundle/Resources/config/routing.yml"
    prefix:   /api

sebk_small_user:
    resource: "@SebkSmallUserBundle/Resources/config/routing.yml"
    prefix:   /api

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
