services:
#    sebk_small_user.example:
#        class: Sebk\SmallUserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sebk_small_users_provider:
        class: Sebk\SmallUserBundle\UserProvider\SmallUserProvider
        arguments:
            - "SebkSmallUserBundle"
            - "User"